<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Surot_menen_ishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Surot_menen_ishRepository extends EntityRepository
{
}
