<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Suylom_kotoruRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Suylom_kotoruRepository extends EntityRepository
{
}
