services:
#    main.example:
#        class: MainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    main.translate:
        class: MainBundle\Services\MainService
        arguments: ["@doctrine.orm.entity_manager"]

    main.admin.translate:
        class: MainBundle\Admin\TranslateAdmin
        arguments: [~, MainBundle\Entity\Translate, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Переводы, label: Переводы слов }

    main.admin.text_translate:
        class: MainBundle\Admin\TextTranslateAdmin
        arguments: [~, MainBundle\Entity\TextTranslate, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Переводы, label: Переводы текстов }

    main.admin.category:
        class: MainBundle\Admin\CategoryAdmin
        arguments: [~, MainBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Category }

    main.admin.surot.menen.ish:
        class: MainBundle\Admin\Surot_menen_ishAdmin
        arguments: [~, MainBundle\Entity\Surot_menen_ish, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Surot_menen_ish }

    main.admin.suylom.kotoru:
        class: MainBundle\Admin\Suylom_kotoruAdmin
        arguments: [~, MainBundle\Entity\Suylom_kotoru, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Suylom_kotoru }

    main.admin.test:
        class: MainBundle\Admin\TestAdmin
        arguments: [~, MainBundle\Entity\Test, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Test }


